#!/bin/sh -

exec=a.out
hostname=`hostname`
echo -n "======================\n${hostname}\n======================"

arch=`uname -m`
if [ "${arch}" = "x86_64" ] ; then arch="x86-64"; fi  # rpmalloc screws up here

if [ ${hostname} = "plg2" ] ; then
    allocsdir="${HOME}/software/llheap"
    allocators="libllheap.so"
else
#    allocsdir="${HOME}/software/allocators"
    allocsdir="${HOME}/software/mimalloc-bench/extern"
#    allocators="glibc libhoard.so libjemalloc.so.2 libllheap.so libmimalloc.so.2 libtbbmalloc.so libtcmalloc.so" # librpmalloc.so
    allocators="glibc dh/build/libdiehard.so ff/libffmallocnpmt.so hd/src/libhoard.so hm/out-light/libhardened_malloc-light.so iso/build/libisoalloc.so je/lib/libjemalloc.so ll/libllheap.so lp/Source/bmalloc/libpas/build-cmake-default/Release/libpas_lib.so lt/gnu.make.lib/libltalloc.so mesh/build/lib/libmesh.so mi3/out/release/libmimalloc.so mng/libmallocng.so rp/bin/linux/release/${arch}/librpmalloc.so scudo/compiler-rt/lib/scudo/standalone/libscudo.so sn/release/libsnmallocshim.so tbb/bench_release/libtbbmalloc_proxy.so tc/.libs/libtcmalloc_minimal.so yal/yalloc.so"
#    allocators="ll/libllheap-stats.so"
fi

cflag="-g -O3 -Wall -Wextra -DNDEBUG -D${hostname}" # -DLINEARAFF
if [ "${hostname}" = "algol" -o "${hostname}" = "prolog" ] ; then # ARM
#    atomicinst=-mno-outline-atomics	# use ARM LL/SC instructions for atomics
    atomicinst=-march=armv8.2-a+lse	# use ARM LSE instructions for atomics
    cflag=${cflag}" ${atomicinst}"
fi

# select newest compiler available for OS
osversion=`lsb_release -sr`
if [ "${osversion}" = "24.04" ] ; then
    CC=g++-14
elif [ "${osversion}" = "22.04" ] ; then
    CC=g++-12
elif [ "${osversion}" = "20.04" ] ; then
    CC=g++-10
else
    echo "unknown operating system"
    exit 1
fi

# force initial thread to start on socket boundary
if [ "${hostname}" = "swift" -o "${hostname}" = "plg2" ] ; then
#    taskset="taskset --cpu-list 128-256"  # upper socket
    taskset=
elif [ "${hostname}" = "java" ] ; then
    taskset=
elif [ "${hostname}" = "prolog" ] ; then
    taskset=
elif [ "${hostname}" = "algol" ] ; then
    taskset=
else
    echo -n "\nUsage error unknown machine name "${hostname}."\n"
    exit 1
fi

#strace='strace -cfq'
time='/usr/bin/time -f "%Uu %Ss %er %Mkb"'
#perf='perf stat -B -e cache-references,cache-misses'
timeout='timeout -k 1 600'

#program="reallocshort"
program="realloclong"
#program="reallocsim"

dims="4 8 16 32"
if [ "${program}" = "reallocshort" ] ; then
   dims=0
fi

for allocator in ${allocators} ; do
    allocatorname=`echo ${allocator} | sed -e "s@\([a-zA-Z0-9]*\)/.*.so@\1@"`
    echo -n "\n\n\"${allocatorname}\"\n"

    for dim in ${dims} ; do
        # compile with preload => dynamic linking
	#echo "${CC} ${cflag} -DDIM=${dim} ${program}.cc -lpthread"
	${CC} ${cflag} -DDIM=${dim} ${program}.cc -lpthread

	if [ "${allocator}" != "glibc" ] ; then
	    export LD_PRELOAD=${allocsdir}/${allocator}
	    #echo "${LD_PRELOAD}"
	fi

	eval ${time} ${strace} ${timeout} ${taskset} ${perf} ./${exec} ${args}

	if [ "${allocator}" != "glibc" ] ; then # turn off allocator as some fail in shell
	    unset LD_PRELOAD
	fi
    done
done

rm -f core
rm -f "${exec}"

exit 0
